export const dummyCities = [
  "All",
  "Daxi",
  "Hongwansi",
  "Sekongkang Bawah",
  "Bunisari",
  "Sobral",
  "Basseterre",
  "Bigoudine",
  "Kabaty",
  "Yessentukskaya",
  "Li’an",
  "Santa Cruz",
  "Mönchengladbach",
  "Zhongzhai",
  "Kudang",
  "Tamano",
  "Edissiya",
  "Saryshaghan",
  "Trnovska Vas",
  "Steinkjer",
  "Dzerzhinsk",
  "Helsingborg",
  "Pajung",
  "Cobh",
  "Hexi",
  "Armenia",
  "Xihe",
  "Horodyshche",
  "Napu",
  "Ta Phraya",
  "Qingxi",
  "Artur Nogueira",
  "Carhué",
  "Yonghe",
  "Koutsopódi",
  "Kuroishi",
  "Rodatychi",
  "Barra do Bugres",
  "Dasha",
  "Pulorejo",
  "Nykarleby",
  "Wilfrido Loor Moreira",
  "Chambéry",
  "La Guadalupe",
  "Sahnaiya",
  "Baucau",
  "Mache",
  "Vamvakoú",
  "Abbeville",
  "Tamel",
  "Can-Avid",
  "Alpedrinha",
  "Ramos West",
  "Cheping",
  "Khanāşir",
  "Bartošovice",
  "Krajan",
  "Chipinge",
  "Da’anshan",
  "Vaasa",
  "Kloangpopot",
  "København",
  "Verkhniy Yasenov",
  "Kandang Timur",
  "Khromtau",
  "Vesele",
  "Arlington",
  "Rio das Pedras",
  "Żarnów",
  "Soloneshnoye",
  "Sigu",
  "Lieyu",
  "Waiklibang",
  "Heshui",
  "Khvalynsk",
  "Głogów Małopolski",
  "Bangkok",
  "Khyzy",
  "Niutang",
  "Tadabliro",
  "Stockholm",
  "Paraiso",
  "Saint Petersburg",
  "Salām Khēl",
  "Gangkoujie",
  "Izmaylovo",
  "Boa Vista",
  "Wagini",
  "Praszka",
  "Talalayivka",
  "Idi Iroko",
  "Pawili",
  "Kurgan",
  "Pasarkolot",
  "Turrialba",
  "Huurch",
  "Gabao",
  "Turbo",
  "Sulmierzyce",
  "Maple Plain",
  "Groblersdal",
];

export const pickerValues = () => {
  const pickerValues = dummyCities.map((item) => {
    return {
      label: item, value: item
    };
  });
  return pickerValues
}